version: "3"

services:
  mqtt:
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    volumes:
      #- ./config/mosquitto:/mosquitto/config
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log
    ports:
      - "9001:9001"

  broker:
    image: ghcr.io/freifunkmuc/wgkex:latest
    command: broker
    restart: unless-stopped
    ports:
      - "5000:5000"
      #volumes:
      #- ./config/broker/wgkex.yaml:/etc/wgkex.yaml
    environment:
      WGKEX_DOMAINS: ${WGKEX_DOMAINS-ffmuc_muc_cty, ffmuc_muc_nord, ffmuc_muc_ost, ffmuc_muc_sued, ffmuc_muc_west, ffmuc_welt, ffwert_city}
      WGKEX_DOMAIN_PREFIXES: ${WGKEX_DOMAIN_PREFIXES-ffmuc_, ffdon_, ffwert_}
      WGKEX_DEBUG: ${WGKEX_DEBUG-DEBUG}
      MQTT_BROKER_URL: ${MQTT_BROKER_URL-mqtt}
      MQTT_BROKER_PORT: ${MQTT_BROKER_PORT-1883}
      MQTT_USERNAME: ${MQTT_USERNAME-}
      MQTT_PASSWORD: ${MQTT_PASSWORD-}
      MQTT_KEEPALIVE: ${MQTT_KEEPALIVE-5}
      MQTT_TLS: ${MQTT_TLS-False}

  worker:
    image: ghcr.io/freifunkmuc/wgkex:latest
    command: worker
    restart: unless-stopped
    #volumes:
    #- ./config/worker/wgkex.yaml:/etc/wgkex.yaml
    environment:
      WGKEX_DOMAINS: ${WGKEX_DOMAINS-ffmuc_muc_cty, ffmuc_muc_nord, ffmuc_muc_ost, ffmuc_muc_sued, ffmuc_muc_west, ffmuc_welt, ffwert_city}
      WGKEX_DOMAIN_PREFIXES: ${WGKEX_DOMAIN_PREFIXES-ffmuc_, ffdon_, ffwert_}
      WGKEX_DEBUG: ${WGKEX_DEBUG-DEBUG}
      MQTT_BROKER_URL: ${MQTT_BROKER_URL-mqtt}
      MQTT_BROKER_PORT: ${MQTT_BROKER_PORT-1883}
      MQTT_USERNAME: ${MQTT_USERNAME-}
      MQTT_PASSWORD: ${MQTT_PASSWORD-}
      MQTT_KEEPALIVE: ${MQTT_KEEPALIVE-5}
      MQTT_TLS: ${MQTT_TLS-False}
