name: Bazel tests

on: [push, pull_request]

jobs:
  bazel-run:
    runs-on: ubuntu-latest
    steps:
      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel
      - uses: actions/checkout@v4
      - name: Run Bazel tests
        run: bazel test ...:all --test_output=all --action_env=WGKEX_CONFIG_FILE=`pwd`/wgkex.yaml.example
      - name: Python coverage
        run: |
          sudo apt-get install -y lcov
          mkdir "${GITHUB_WORKSPACE}/src"
          cd "${GITHUB_WORKSPACE}/src"
          curl -L https://files.pythonhosted.org/packages/84/ba/ac14d281f80aab516275012e8875991bb06203957aa1e19950139238d658/coverage-7.6.10.tar.gz | tar xvz
          cd "${GITHUB_WORKSPACE}"
          bazel coverage --combined_report=lcov --javabase=@bazel_tools//tools/jdk:remote_jdk11 -t- --instrument_test_targets \
            --experimental_cc_coverage --test_output=errors --linkopt=--coverage --linkopt=-lc \
            --test_env=PYTHON_COVERAGE=${GITHUB_WORKSPACE}/src/coverage-7.6.10/__main__.py  \
            --define=config_file=test ...:all
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: bazel-out/_coverage/_coverage_report.dat
